name: Symfony CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      run: |
        sudo add-apt-repository -y ppa:ondrej/php
        sudo apt-get update
        sudo apt-get install -y php7.4-cli php7.4-xml

    - name: Set up .env file
      run: cp .env.example .env && cp web/.env.example web/.env

    - name: Install Composer Dependencies
      working-directory: ./web
      run: composer install

    - name: Set up Symfony Environment
      working-directory: ./web
      run: php bin/console --no-interaction doctrine:database:create --env=test
          
    - name: Run PHPUnit Tests
      working-directory: ./web
      run: php bin/phpunit

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: test

  #   steps:
  #   - name: Upload to Server via SCP
  #     uses: appleboy/scp-action@v0.3.0
  #     with:
  #       host: ${{ secrets.SSH_HOST }}
  #       username: ${{ secrets.SSH_USERNAME }}
  #       key: ${{ secrets.SSH_PRIVATE_KEY }}
  #       port: ${{ secrets.SSH_PORT }}
  #       source: './*'
  #       target: '/path/to/your/server/directory'
